name: "chatGPT Algorithm Mentor"
description: "algorithm code review using chatGPT"
author: "choam2426"
inputs:
  GITHUB_TOKEN:
    description: "github token"
    required: true
  OPENAI_API_KEY:
    description: "openai api key"
    required: true
  COMMIT_SHA:
    description: "latest commit sha"
    required: true
runs:
  using: "docker"
  image: "choam2426/chatgpt_algorithm_mentor:latest"
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    COMMIT_SHA: ${{ inputs.COMMIT_SHA }}
