name: "ChatGPT Algorithm Mentor"
description: "algorithm code review using ChatGPT"
author: "choam2426"
inputs:
  GITHUB_TOKEN:
    description: "github token"
    required: true
  OPENAI_API_KEY:
    description: "openai api key"
    required: true
  COMMIT_SHA:
    description: "latest commit sha"
    required: true
  LANGUAGE:
    description: "mentor output language"
    default: KOREAN
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    COMMIT_SHA: ${{ inputs.COMMIT_SHA }}
    LANGUAGE: ${{ inputs.LANGUAGE }}
    