name: "ChatGPT Algorithm Code Review"
description: "algorithm code review using ChatGPT"
author: "choam2426"
inputs:
  GITHUB_TOKEN:
    description: "github token"
    required: true
  OPENAI_API_KEY:
    description: "openai api key"
    required: true
  MODEL:
    description: "openai api model"
    default: "gpt-4o"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    MODEL: ${{ inputs.MODEL }}
    COMMIT_SHA: ${{ github.sha}}
