name: gpt algorithm mentor

on:
  push:
    branches: [ "main" ]

jobs:
  write comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: choam2426/GPT-algorithm-code-review@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          COMMIT_SHA: ${{ github.sha }}
          LANGUAGE: ENGLISH # 응답 언어를 지정하세요