name: gpt algorithm mentor

on:
  push:
    branches: [ "main" ]

jobs:
  write_comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: choam2426/GPT-algorithm-code-review@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # OPENAI API 크레딧 필요
          COMMIT_SHA: ${{ github.sha }}